#!/usr/bin/env bash
# =============================================================================
# 02_download_maf_files.sh
# Download all TCGA-LAML masked somatic mutation MAF files from GDC.
# Requires manifest_uuids.txt generated by 01_get_tcga_manifest.sh
#
# Output: data/tcga_maf/<uuid>/<filename>.maf.gz (153 files)
#
# Usage: bash scripts/part2_aml_cohort/02_download_maf_files.sh
# =============================================================================

set -euo pipefail

MANIFEST="data/tcga_maf/manifest_uuids.txt"
OUTDIR="data/tcga_maf"

if [[ ! -f "${MANIFEST}" ]]; then
    echo "[ERROR] Manifest not found. Run 01_get_tcga_manifest.sh first."
    exit 1
fi

echo "[INFO] Downloading $(wc -l < ${MANIFEST}) MAF files from GDC..."

curl -o "${OUTDIR}/TCGA-LAML-MAF-files.tar.gz" \
    -X POST \
    -H "Content-Type: application/json" \
    -d "{\"ids\": $(python3 -c "
import json
uuids = open('${MANIFEST}').read().strip().split('\n')
print(json.dumps(uuids))
")}" \
    "https://api.gdc.cancer.gov/data"

echo "[INFO] Extracting archive..."
tar -xzf "${OUTDIR}/TCGA-LAML-MAF-files.tar.gz" -C "${OUTDIR}/"

echo "[INFO] Done. MAF files extracted to ${OUTDIR}/"